name: Build and test code
on:
  pull_request:
  push:
    branches: [main]

jobs:
  run-tests:
    runs-on: zon-ubuntu-general-dind
    env:
      GO_VERSION: "1.25"
    steps:
      - uses: actions/checkout@v4
      - name: Setup golang
        uses: actions/setup-go@v5
        with:
          go-version: "^${{ env.GO_VERSION }}"
          cache: true
          cache-dependency-path: go.sum
      - run: mkdir cmd/test_artifacts
      - run: go test -v -cover ./...
