name: Build and test code
on:
  pull_request:
  push:
    branches: [main]

jobs:
  run-tests:
    runs-on: zon-ubuntu-general-dind
    env:
      GO_VERSION: "1.25"
    steps:
      - uses: actions/checkout@v4
      - name: Setup golang
        uses: actions/setup-go@v5
        with:
          go-version: "^${{ env.GO_VERSION }}"
      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: go-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-${{ env.GO_VERSION }}-
      - run: mkdir cmd/test_artifacts
      - run: go test -v -cover ./...
